# This is a demo config file showing a minimal set of default keys and keys used by the theme.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
footer_copyright: Name of Copyright Holder
logo: /assets/logo_invisible.svg
favicon: /assets/logo.svg

navigation_header:
- title: Home
  url: /
- title: One
  url: /one/
- title: Two
  url: /two/
- title: Three
  url: /three/
